name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution:  'temurin'

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          export JMETER_HOME=$(pwd)/apache-jmeter-5.6.3
          export PATH=$PATH:$JMETER_HOME/bin

      - name: Run JMeter Test
        run: |
          mkdir -p results/Reports
          ./apache-jmeter-5.6.3/bin/jmeter -n -t BlazeDemo_Test_Plan.jmx -l results/results.csv -e -o results/Reports

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/Reports
