name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          export JMETER_HOME=$(pwd)/apache-jmeter-5.6.3
          export PATH=$PATH:$JMETER_HOME/bin

      - name: Run JMeter Test (JTL)
        run: |
          mkdir -p results_jtl/Reports
          ./apache-jmeter-5.6.3/bin/jmeter -n -t BlazeDemo_Test_Plan.jmx -l results_jtl/results.jtl -e -o results_jtl/Reports

      - name: Run JMeter Test (CSV)
        run: |
          mkdir -p results_csv/Reports
          ./apache-jmeter-5.6.3/bin/jmeter -n -t BlazeDemo_Test_Plan.jmx -l results_csv/results.csv -e -o results_csv/Reports

      - name: Upload JTL Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-jtl
          path: results_jtl/Reports

      - name: Upload CSV Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-csv
          path: results_csv/Reports
